### ISSUE TITLE
Tidy requests

### ISSUE THREAD

**Issue by hashstudiobackend** [ayaatadel/twitter_clone#1]
https://github.com/ayaatadel/twitter_clone/blob/d3de069a3f3c1ef008a89c61fb565af866d0cbd1/app/Http/Controllers/PostsController.php#L41

Use FormRequests classes tidy up your code and separate validation logic from other processes (like interacting with database). Read more about [here](https://laravel.com/docs/8.x/validation#form-request-validation)

**Comment by ayaatadel** [comment]
Done
