### ISSUE TITLE
Saving inputs from Request class

### ISSUE THREAD

**Issue by hashstudiobackend** [ayaatadel/twitter_clone#2]
https://github.com/ayaatadel/twitter_clone/blob/d3de069a3f3c1ef008a89c61fb565af866d0cbd1/app/Http/Controllers/PostsController.php#L48-L51

You can save input directly from 3 magic request class' methods:

1- $request->only(['body', 'user_id']);
returns only body and user_id values.

2- $request->except(['img']);
returns all values except img value

3- $request->validated();
returns only valid inputs according to your validation rules

Read more about them [here](https://laravel.com/docs/8.x/validation#working-with-validated-input)

So, the code might be like following

```php
$data = $request->validated();
$data['img'] = 'tmp.jpg';

$post = Post::create($data);
```

**Comment by ayaatadel** [comment]
Done
