### ISSUE TITLE
DRY: Separate image in base controller class

### ISSUE THREAD

**Issue by hashstudiobackend** [ayaatadel/twitter_clone#3]
https://github.com/ayaatadel/twitter_clone/blob/d3de069a3f3c1ef008a89c61fb565af866d0cbd1/app/Http/Controllers/PostsController.php#L52-L63

You might need to use the logic of uploading image many times in your code. To save your time and keep your code DRY, you can add the logic of **uploading image** in base [Controller](https://github.com/ayaatadel/twitter_clone/blob/master/app/Http/Controllers/Controller.php).

To make it reusable you should return only image name from the new method. For example:

```php
protected function uploadImage(Request $request, string $folder, string $input = 'image')
{
         if ($request->has($input)) {
              return Storage::disk('public')->putFile(
                $folder,
                $request->file($input)
            );
        }

       return null;
}
```

Note that, both `putFile` and `putFileAs` return hashed filed name with its extension, [read more here](https://laravel.com/docs/8.x/filesystem#automatic-streaming)

**Comment by ayaatadel** [comment]
Done
